"""Shopify products.csv exporter.

Reads a `pipeline_manifest.jsonl` produced by `comfybulk pipeline --write-manifest`
(see :func:`comfybulk.pipeline._write_manifest`) and emits a CSV that drops cleanly
into the Shopify Admin "Products" import surface. One row per generated output
asset; each row points at the local output path under `Image Src` so the operator
can upload assets and rewrite the column with the resulting CDN URL.

The header order intentionally matches the canonical column order in the Shopify
import template — the importer is positional in practice (it tolerates extras but
fails silently on reorder for some columns), so we anchor to the official order.
Reference: https://help.shopify.com/en/manual/products/import-export/using-csv
"""
from __future__ import annotations

import csv
import json
import re
from dataclasses import dataclass
from pathlib import Path
from typing import Iterable, Iterator


# Canonical Shopify products.csv column order (Shopify Admin import template).
SHOPIFY_HEADERS: tuple[str, ...] = (
    "Handle",
    "Title",
    "Body (HTML)",
    "Vendor",
    "Product Category",
    "Type",
    "Tags",
    "Published",
    "Option1 Name",
    "Option1 Value",
    "Option2 Name",
    "Option2 Value",
    "Option3 Name",
    "Option3 Value",
    "Variant SKU",
    "Variant Grams",
    "Variant Inventory Tracker",
    "Variant Inventory Qty",
    "Variant Inventory Policy",
    "Variant Fulfillment Service",
    "Variant Price",
    "Variant Compare At Price",
    "Variant Requires Shipping",
    "Variant Taxable",
    "Variant Barcode",
    "Image Src",
    "Image Position",
    "Image Alt Text",
    "Gift Card",
    "SEO Title",
    "SEO Description",
    "Status",
)


_HANDLE_STRIP = re.compile(r"[^a-z0-9]+")


def _slugify(value: str) -> str:
    """Shopify Handle: lowercase, hyphen-separated, ASCII-only."""
    slug = _HANDLE_STRIP.sub("-", value.lower()).strip("-")
    return slug or "untitled"


def _titlecase(stem: str) -> str:
    cleaned = re.sub(r"[_\-]+", " ", stem).strip()
    return cleaned.title() if cleaned else "Untitled"


@dataclass(frozen=True)
class ShopifyDefaults:
    vendor: str = "Wranngle"
    product_type: str = "Generative Video"
    price: str = "0.00"
    published: str = "FALSE"
    status: str = "draft"
    inventory_policy: str = "deny"
    fulfillment_service: str = "manual"
    requires_shipping: str = "FALSE"
    taxable: str = "TRUE"
    gift_card: str = "FALSE"


def _iter_manifest(manifest_path: Path) -> Iterator[dict]:
    with manifest_path.open("r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                entry = json.loads(line)
            except json.JSONDecodeError:
                continue
            if entry.get("event") != "pipeline_run":
                continue
            yield entry


def manifest_to_rows(
    manifest_path: Path,
    *,
    defaults: ShopifyDefaults | None = None,
) -> list[dict]:
    """Flatten a pipeline manifest into one row per output asset."""
    defaults = defaults or ShopifyDefaults()
    rows: list[dict] = []
    seen_handles: dict[str, int] = {}
    for entry in _iter_manifest(manifest_path):
        variant = entry.get("variant", "asset")
        timestamp = entry.get("timestamp") or entry.get("completed_at") or ""
        for position, output in enumerate(entry.get("outputs", []) or [], start=1):
            stem = Path(output).stem or variant
            title = _titlecase(stem)
            base_handle = _slugify(stem)
            handle = base_handle
            count = seen_handles.get(base_handle, 0)
            if count:
                handle = f"{base_handle}-{count + 1}"
            seen_handles[base_handle] = count + 1
            body_html = (
                f"<p>Generated by comfybulk pipeline variant <strong>{variant}</strong>"
                f" at {timestamp}.</p>"
            )
            tags = ",".join(t for t in (variant, "comfybulk", "ai-generated") if t)
            row = {h: "" for h in SHOPIFY_HEADERS}
            row.update({
                "Handle": handle,
                "Title": title,
                "Body (HTML)": body_html,
                "Vendor": defaults.vendor,
                "Type": defaults.product_type,
                "Tags": tags,
                "Published": defaults.published,
                "Variant SKU": f"CB-{handle}",
                "Variant Inventory Policy": defaults.inventory_policy,
                "Variant Fulfillment Service": defaults.fulfillment_service,
                "Variant Price": defaults.price,
                "Variant Requires Shipping": defaults.requires_shipping,
                "Variant Taxable": defaults.taxable,
                "Image Src": output,
                "Image Position": str(position),
                "Image Alt Text": title,
                "Gift Card": defaults.gift_card,
                "SEO Title": title,
                "SEO Description": body_html,
                "Status": defaults.status,
            })
            rows.append(row)
    return rows


def export_shopify_csv(
    manifest_path: str | Path,
    output_csv: str | Path,
    *,
    defaults: ShopifyDefaults | None = None,
) -> int:
    """Write a Shopify-compatible products.csv next to (or wherever caller wants).

    Returns the number of rows written (excluding the header).
    """
    manifest = Path(manifest_path)
    if not manifest.is_file():
        raise FileNotFoundError(f"manifest not found: {manifest}")
    rows = manifest_to_rows(manifest, defaults=defaults)
    out = Path(output_csv)
    out.parent.mkdir(parents=True, exist_ok=True)
    with out.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(f, fieldnames=list(SHOPIFY_HEADERS))
        writer.writeheader()
        writer.writerows(rows)
    return len(rows)


def asset_count(manifest_path: str | Path) -> int:
    """Count output assets recorded in the manifest. Used as proof oracle."""
    total = 0
    for entry in _iter_manifest(Path(manifest_path)):
        total += len(entry.get("outputs", []) or [])
    return total
