name: '🐛 Bug report'
description: 'Report a bug to help us improve the project.'
labels: ['bug']
body:
  - type: markdown
    attributes:
      value: 'Thanks for taking the time to report a bug!'
  - type: textarea
    id: what-happened
    attributes:
      label: 'What happened?'
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: 'What did you expect?'
  - type: textarea
    id: repro
    attributes:
      label: 'Reproduction steps'
  - type: input
    id: environment
    attributes:
      label: 'Environment'
      description: 'OS, version, runtime'
  - type: input
    id: version
    attributes:
      label: '.dotfiles version'
